# Generated by Django 4.1.3 on 2022-11-22 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='title',
            field=models.CharField(default='', max_length=200),
        ),
    ]
