# Generated by Django 4.1.3 on 2022-11-24 07:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0002_match_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='match_time',
            field=models.TimeField(default=datetime.datetime(2022, 11, 24, 7, 20, 47, 527307, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='match',
            name='match_date',
            field=models.DateField(),
        ),
    ]
