# Generated by Django 4.1.3 on 2023-03-14 05:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('match', '0004_alter_match_match_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='participants',
            field=models.ManyToManyField(related_name='matches_participating', to=settings.AUTH_USER_MODEL),
        ),
    ]
