# Generated by Django 4.1.3 on 2023-03-14 08:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifc', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 14, 8, 17, 48, 315058)),
        ),
    ]
