# Generated by Django 4.1.3 on 2023-03-14 08:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifc', '0002_notification_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 14, 8, 18, 29, 776204, tzinfo=datetime.timezone.utc)),
        ),
    ]
